title: <p align="center"> Rohit Ghosh </p>

logo: "images/croping39.png"

description:
  <p align="center">
  <a href="pdf/Rohit Ghosh Resume FT2.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/rohit-ghosh7797/">LinkedIn</a> |
  <a href="https://github.com/rohitghsh">GitHub</a>
  </p>
  
  <p align="justify">
 Experienced Data Scientist with a Master’s in Business Analytics and Project Management, 
 bringing 3+ years of expertise in developing data-intensive applications. Specialized in 
 customer segmentation, skilled in predictive modeling, data processing, and data mining 
 using Python, R, SQL, and adept at visualization with Power BI. Translates business needs 
 into impactful deliverables.
  </p>

show_downloads: False
theme: jekyll-theme-minimal
